---
name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install zsh
        run: |
          sudo apt-get update
          sudo apt-get install zsh

      - name: pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Run tests
        run: |
          cd tests
          ./run_tests.sh

